{
    "name": "School Application",
    "summary": "USe for School Management",
    "author": "BizzAppDev Systems Pvt. Ltd",
    "website": "https://bizzappdev.com",
    "version": "15.0.1.0.0",
    "license": "LGPL-3",
    "application": True,
    "installable": True,
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/student_details_views.xml",
        "views/result_details_views.xml",
        "views/teacher_details_views.xml",
        "views/subject_details_views.xml",
        "views/exam_details_views.xml",
        "views/event_details_views.xml",
        "views/principal_details_views.xml",
        "views/hostel_details_views.xml",
        "views/res_config_settings_views.xml",
        "views/school_menu_views.xml",
    ],
    "depends": ["base", "mail"],
    "category": "Services/School Application",
}
